results_folder: /media/joebillingsley/Data/projects/NFV_AG_Journal/temp
num_evaluations: 12000
num_runs: 30
test_sizes: 0 #All
num_splits: 4

perc_nearest: 0.15

num_weights: 16
per_ind_evaluations: 10

accuracy: 5.0
converged_iterations: 10
port_sr: 20.0
port_ql: 20.0
active_cost: 30.0
idle_cost: 10.0

mean_service_len: 5.0
variance_service_len: 1.0
min_service_len: 2.0
max_service_len: 12.0

mean_prod_rate: 10.0
variance_prod_rate: 3.0
min_prod_rate: 0.1

mean_service_rate: 10.0
variance_service_rate: 3.0
min_service_rate: 1.0

vnf_queue_length: 20

mean_vnf_size: 40.0
variance_vnf_size: 10.0

utilisation: 0.6